P1_CodFac/models/User.py
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash
from werkzeug.security import check_password_hash
import datetime

db = SQLAlchemy()

class User(db.Model):
    __tablename__='users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    email = db.Column(db.String(40),unique=True)
    password = db.Column(db.String(66))
    create_date = db.Column(db.DateTime,default=datetime.datetime.now)
    
    def __init__(self,username,email,password):
        self.username = username
        self.email = email
        self.password = self.create_password(password)
    
    def create_password(self,password):
        return generate_password_hash(password)
    def verify_password(self,password):
        return check_password_hash(self.password, password)

P1_CodFac/app.py
from flask import Flask
from routes.login import logeo
from flask_sqlalchemy import SQLAlchemy
from config.config import DevelopmentConfig
from models.User import db

app = Flask(__name__)
app.config.from_object(DevelopmentConfig)
db = SQLAlchemy(app)

# app.register_blueprint(listar)
app.register_blueprint(logeo)

if __name__ == '__main__':
    db.init_app(app)
    with app.app_context():
        db.create_all()
    app.run()

P1_CodFac/routes/login.py
# para crear rutas personalizadas
from flask import Blueprint
from flask import render_template, request, url_for, flash, g
from flask import session
from werkzeug.utils import redirect
from models.User import User
from utils.db import db

logeo = Blueprint('login',__name__)

@logeo.before_app_request
def before_request_login():
    g.user = session.get('email') 
    if g.user is None and request.endpoint in ['login.static','login.logout','login.index']:
        return redirect(url_for('login.register'))
    elif g.user is not None and request.endpoint in ['login.login','login.register','login.static']:
        return redirect(url_for('login.index'))
        
@logeo.after_app_request
def after_request_login(response):
    return response

@logeo.route('/')
def index():
    usuarios = User.query.all()
    return render_template('lista/lista.html',listado = usuarios)

@logeo.route('/login',methods=['POST','GET'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()
        if user is not None and user.verify_password(password):
            session['email'] = email
            flash(f'Usuario {user.username} logeado correctamente')
            return redirect(url_for('login.index'))
        else:
            flash(f'Contraseña o correo no validos')
    return render_template('login/login.html')

@logeo.route('/logout')
def logout():
    if g.user:
        session.pop('email')
    return redirect(url_for('login.login'))

@logeo.route('/registerUser', methods=['POST','GET'])
def register():
    if request.method == 'POST':
        userName = request.form['userName']
        email = request.form['email']
        password = request.form['password']
        V_user = User.query.filter_by(email=email).first()
        if V_user is None:
            newUser = User(userName,email,password)
            db.session.add(newUser)
            db.session.commit()
            session['email'] = email
            flash(f'usuario {email} creado')
            return redirect(url_for('login.index'))
        else:
            flash('El usuario ya existe')
    return render_template('login/register.html')

@logeo.route('/deleteUser/<int:id>')
def delete(id):
    usuario = db.session.query(User).get(id)
    # usuario = User.query.get(id)
    if g.user == usuario.email:
        session.pop('email')
    db.session.delete(usuario)
    db.session.commit()
    return redirect(url_for('login.index'))

@logeo.route('/updateUser/<int:id>',methods=['POST','GET'])
def update(id):
    usuario = db.session.query(User).get(id)
    if request.method == 'POST':
        usuario.username = request.form['userName']
        usuario.email = request.form['email']
        db.session.commit()
        return redirect(url_for('login.index'))
    return render_template('login/update.html',usuario=usuario)

P1_CodFac/templates/empleados/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
    <title>Document</title>
</head>
<body>
    INDEX<br>
    {% block content %}
    {% endblock %}
</body>
</html>

P1_CodFac/templates/lista/lista.html
{% extends 'empleados/index.html'%}
{% block content %}
LISTA
{% with messages = get_flashed_messages() %}  
    {% if messages %}
        {% for mensaje in messages %}
            <div class="mensaje">
                {{ mensaje }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}
{% for item in listado %}
<div>
    <h2>Usuario: {{item.username}}</h2>
    <p>Email: {{item.email}}</p>
    <p>Date: {{item.create_date}}</p>
    <a href="{{url_for('login.delete',id=item.id)}}">DELETE</a>
    <a href="{{url_for('login.update',id=item.id)}}">UPDATE</a>
</div>
{% endfor %}
{% endblock %}

P1_CodFac/templates/login/login.html
{% extends 'empleados/index.html' %}
{% block content %}
LOGIN
{% with messages = get_flashed_messages() %}  
    {% if messages %}
        {% for mensaje in messages %}
        <div class="mensaje">
            {{ mensaje }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<form action="/login" method="POST">
    {% from 'macros/inputs.html' import input_login %}
    {{ input_login() }}
</form>
{% endblock %}

P1_CodFac/templates/login/register.html
{% extends 'empleados/index.html' %}
{% block content %}
REGISTER
{% with messages = get_flashed_messages() %}  
    {% if messages %}
        {% for mensaje in messages %}
        <div class="mensaje">
            {{ mensaje }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}   
<form action="/registerUser" method="POST">
    {% from 'macros/inputs.html' import input_register %}
    {{ input_register() }}
</form>
{% endblock %}

P1_CodFac/templates/login/update.html
{% extends 'empleados/index.html' %}
{% block content %}
REGISTER
<form action="/updateUser/{{usuario.id}}" method="POST">
    {% from 'macros/inputs.html' import input_update %}
    {{ input_update(usuario) }}
</form>
{% endblock %}

P1_CodFac/templates/macros/inputs.html
{% macro input_login() %}
    <input type="email" name="email" placeholder="email">
    <input type="password" name="password" placeholder="password">
    <input type="submit" value="Enviar">
{% endmacro%}

{% macro input_register() %}
    <input type="text" name="userName" placeholder="username">
    <input type="email" name="email" placeholder="email">
    <input type="password" name="password" placeholder="password">
    <input type="submit" value="Enviar">
{% endmacro%}

{% macro input_update(value) %}
    <input type="text" name="userName" placeholder="username" value="{{value.username}}">
    <input type="email" name="email" placeholder="email" value="{{value.email}}">
    <input type="submit" value="Enviar">
{% endmacro%}